<?php
defined( 'ABSPATH' ) || exit;

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5ec2a6e96c5c9',
        'title' => 'Cats metadata',
        'fields' => array(
            array(
                'key' => 'field_5ec2a719f89e9',
                'label' => __( 'Name', 'kks' ),
                'name' => 'cat_name',
                'type' => 'text',
                'instructions' => __( 'Name of the cat.', 'kks' ),
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5ec2a746f89ea',
                'label' => __( 'Age', 'kks' ),
                'name' => 'cat_age',
                'type' => 'date_picker',
                'instructions' => __('Birthdate of the cat.', 'kks'),
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'd/m/Y',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_5ec2a7b7f89eb',
                'label' =>  __( 'Color', 'kks' ),
                'name' => 'cat_color',
                'type' => 'text',
                'instructions' =>  __( 'Color of the cat.', 'kks' ),
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5ec2a7d3f89ec',
                'label' =>  __( 'Weight', 'kks' ),
                'name' => 'cat_weight',
                'type' => 'number',
                'instructions' =>  __( 'Cats weight in kg.', 'kks' ),
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 1,
                'max' => 50,
                'step' => '',
            ),
            array(
                'key' => 'field_5ec429e7fac52',
                'label' =>  __( 'Adopted', 'kks' ),
                'name' => 'cat_adopted',
                'type' => 'select',
                'instructions' => __('Is the cat adopted? Yes/No
    If yes pick the date under here.', 'kks'),
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Yes' => __( 'Yes', 'kks' ),
                    'No' => 'No',
                ),
                'default_value' => 'No',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5ec2a817f89ed',
                'label' =>  __( 'Date adopted', 'kks' ),
                'name' => 'cat_date_adopted',
                'type' => 'date_picker',
                'instructions' => __('Pick the date when the cat was adopted.', 'kks'),
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5ec429e7fac52',
                            'operator' => '==',
                            'value' => 'Yes',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'd/m/Y',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_5ec2a86bf89ee',
                'label' => __('Description', 'kks'),
                'name' => 'cat_description',
                'type' => 'textarea',
                'instructions' => __('Something to share about the cat.', 'kks'),
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5ec2a8a7f89ef',
                'label' =>  __( 'Image', 'kks' ),
                'name' => 'cat_image',
                'type' => 'image',
                'instructions' => __('A photo on the cat.', 'kks'),
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'large',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'cats',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;